// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiDemo.Data;

#nullable disable

namespace WebApiDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiDemo.Models.Shirt", b =>
                {
                    b.Property<int>("ShirtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShirtId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("ShirtId");

                    b.ToTable("Shirts");

                    b.HasData(
                        new
                        {
                            ShirtId = 1,
                            Brand = "A",
                            Color = "Blue",
                            Gender = "Men",
                            Price = 12,
                            Size = 12
                        },
                        new
                        {
                            ShirtId = 2,
                            Brand = "B",
                            Color = "Red",
                            Gender = "Women",
                            Price = 22,
                            Size = 11
                        },
                        new
                        {
                            ShirtId = 3,
                            Brand = "C",
                            Color = "Green",
                            Gender = "Women",
                            Price = 32,
                            Size = 14
                        },
                        new
                        {
                            ShirtId = 4,
                            Brand = "D",
                            Color = "White",
                            Gender = "Men",
                            Price = 42,
                            Size = 13
                        },
                        new
                        {
                            ShirtId = 5,
                            Brand = "E",
                            Color = "Black",
                            Gender = "Women",
                            Price = 52,
                            Size = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
